
// FLIXYFY_FILTERS_SPEED_AUDIT_FIX_V4
// Cached API reads, provider normalization, webseries/global-search routing, duplicate filter hiding.
const MAP={"":"all",all:"all","all provider":"all","all providers":"all",youtube:"youtube",yt:"youtube","you tube":"youtube",netflix:"netflix",prime:"prime_video","prime video":"prime_video",primevideo:"prime_video",prime_video:"prime_video","amazon prime":"prime_video","amazon prime video":"prime_video",jiohotstar:"jiohotstar","jio hotstar":"jiohotstar",hotstar:"jiohotstar","disney hotstar":"jiohotstar",zee5:"zee5","zee 5":"zee5",sonyliv:"sonyliv","sony liv":"sonyliv",aha:"aha",sunnxt:"sun_nxt","sun nxt":"sun_nxt",sun_nxt:"sun_nxt",etvwin:"etv_win","etv win":"etv_win",etv_win:"etv_win",mxplayer:"mx_player","mx player":"mx_player",mx_player:"mx_player","apple tv":"apple_tv_store",apple_tv:"apple_tv_store","apple tv store":"apple_tv_store",itunes:"apple_tv_store","amazon video":"amazon_video",amazon_video:"amazon_video","google tv":"google_tv",google_tv:"google_tv",disney:"disney_plus","disney+":"disney_plus","disney plus":"disney_plus",disney_plus:"disney_plus",hulu:"hulu",max:"max","hbo max":"max",plex:"plex",viki:"viki","rakuten viki":"viki",kocowa:"kocowa",tving:"tving",wavve:"wavve",watcha:"watcha","coupang play":"coupang_play",coupang_play:"coupang_play",tubi:"tubi_tv","tubi tv":"tubi_tv",tubi_tv:"tubi_tv"};
const LABEL={all:"All Providers",youtube:"YouTube",netflix:"Netflix",prime_video:"Prime Video",jiohotstar:"JioHotstar",zee5:"ZEE5",sonyliv:"SonyLIV",aha:"Aha",sun_nxt:"Sun NXT",etv_win:"ETV Win",mx_player:"MX Player",apple_tv_store:"Apple TV",amazon_video:"Amazon Video",google_tv:"Google TV",disney_plus:"Disney+",hulu:"Hulu",max:"Max",plex:"Plex",viki:"Rakuten Viki",kocowa:"Kocowa",tving:"TVING",wavve:"Wavve",watcha:"Watcha",coupang_play:"Coupang Play",tubi_tv:"Tubi"};
const CACHE=new Map(), INFLIGHT=new Map(), TTL=60000, TIMEOUT=12000;
function clean(v){return String(v||'').trim().toLowerCase().replace(/[+]/g,' plus ').replace(/[_-]+/g,' ').replace(/\s+/g,' ').trim()}
export function normalizeProviderForApi(v){const r=clean(v); if(Object.prototype.hasOwnProperty.call(MAP,r))return MAP[r]; const k=r.replace(/\s+/g,'_'); return MAP[k]||k||'all'}
export function providerValueForState(v){const p=normalizeProviderForApi(v); return p==='all'?'':p}
export function providerDisplayLabel(v){const p=normalizeProviderForApi(v); return LABEL[p]||String(p||'').replace(/_/g,' ').replace(/\b\w/g,m=>m.toUpperCase())}
export function providerFromCurrentUrl(){if(typeof window==='undefined')return''; const p=new URLSearchParams(window.location.search||''); return providerValueForState(p.get('provider')||p.get('provider_key')||'')}
export function syncProviderToUrl(v){if(typeof window==='undefined')return; const p=providerValueForState(v), u=new URL(window.location.href); if(p)u.searchParams.set('provider',p); else u.searchParams.delete('provider'); window.history.replaceState({},'',`${u.pathname}${u.search}${u.hash}`)}
function has(txt,arr){const t=clean(txt); return arr.some(x=>t.includes(x))}
function rewriteUrl(input){const u=new URL(String(input), typeof window!=='undefined'?window.location.origin:'https://flixyfy.com'); const path=u.pathname.replace(/\/+$/,''); const sp=u.searchParams; const provider=providerValueForState(sp.get('provider')||sp.get('provider_key')||''); const availability=clean(sp.get('availability')||sp.get('has_ott')||''); const meta=[sp.get('type'),sp.get('content_type'),sp.get('contentType'),sp.get('media_type'),sp.get('tab'),sp.get('scope'),sp.get('domain'),sp.get('category')].filter(Boolean).join(' '); let endpoint=null; if(has(meta,['webseries','web series','series']))endpoint='/api/v3/webseries'; else if(has(meta,['historical']))endpoint='/api/v3/historical'; else if(has(meta,['hollywood','global']))endpoint='/api/v3/hollywood'; else if(has(meta,['indian','current','movie','movies']))endpoint='/api/v3/movies'; if(!endpoint&&(path==='/api/v3/global-search'||path==='/api/v3/search')&&provider)endpoint='/api/v3/movies'; if(availability.includes('free')){sp.set('provider','youtube'); sp.set('availability','free')} else if(provider){sp.set('provider',provider)} if(endpoint&&(path==='/api/v3/global-search'||path==='/api/v3/search')){u.pathname=endpoint; ['type','content_type','contentType','media_type','tab','scope','domain','category'].forEach(k=>sp.delete(k));} return u}
function keyFor(url){const u=rewriteUrl(url); u.searchParams.sort(); return u.toString()}
export async function fetchFlixyfyJson(url,opt={}){const u=rewriteUrl(url), key=keyFor(u.toString()), now=Date.now(); const c=CACHE.get(key); if(c&&c.expiresAt>now)return c.data; if(INFLIGHT.has(key))return INFLIGHT.get(key); const ctrl=new AbortController(); const timer=window.setTimeout(()=>ctrl.abort(),Number(opt.timeoutMs||TIMEOUT)); const p=fetch(u.toString(),{cache:'no-store',headers:{Accept:'application/json',...(opt.headers||{})},signal:ctrl.signal}).then(async r=>{if(!r.ok){const t=await r.text().catch(()=>''); throw new Error(`API ${r.status}: ${u.toString()} ${t.slice(0,200)}`)} return r.json()}).then(data=>{CACHE.set(key,{data,expiresAt:Date.now()+Number(opt.ttlMs||TTL)}); return data}).finally(()=>{window.clearTimeout(timer); INFLIGHT.delete(key)}); INFLIGHT.set(key,p); return p}
function optTexts(s){return Array.from(s?.options||[]).map(o=>clean(`${o.value||''} ${o.textContent||''}`))}
function isProviderSelect(s){const t=optTexts(s); return t.some(x=>normalizeProviderForApi(x)==='youtube'||x.includes('youtube'))&&t.some(x=>normalizeProviderForApi(x)==='netflix'||x.includes('netflix'))}
function isDuplicateTitleFilter(s){const t=optTexts(s).join(' | '); if(isProviderSelect(s))return false; return t.includes('all titles') || (t.includes('all movies')&&(t.includes('free')||t.includes('ott')||t.includes('stream')))}
function hideDuplicateTitleFilters(){Array.from(document.querySelectorAll('select')).forEach(s=>{if(!isDuplicateTitleFilter(s))return; const w=s.closest('.filter,.filter-control,.select-wrap,.filter-select,label,div')||s; w.style.display='none'; w.setAttribute('data-flixyfy-hidden-duplicate-filter','true')})}
function setProviderToYouTube(){const s=Array.from(document.querySelectorAll('select')).find(isProviderSelect); if(!s)return; const y=Array.from(s.options||[]).find(o=>normalizeProviderForApi(o.value||o.textContent)==='youtube'); if(y&&s.value!==y.value){s.value=y.value; s.dispatchEvent(new Event('change',{bubbles:true}))}}
export function installProviderFetchPatch(){if(typeof document==='undefined'||window.__FLIXYFY_FILTERS_SPEED_AUDIT_FIX_V4__)return{active:false,version:'v4'}; window.__FLIXYFY_FILTERS_SPEED_AUDIT_FIX_V4__=true; hideDuplicateTitleFilters(); new MutationObserver(()=>hideDuplicateTitleFilters()).observe(document.documentElement,{childList:true,subtree:true}); document.addEventListener('change',e=>{const t=e.target; if(!t||t.tagName!=='SELECT')return; const o=t.selectedOptions?.[0]; const txt=clean(`${o?.value||''} ${o?.textContent||''}`); if(!isProviderSelect(t)&&txt.includes('free'))window.setTimeout(setProviderToYouTube,0)},true); return{active:true,version:'v4'}}
export default installProviderFetchPatch;
